Document: pyenv
Title: Debian pyenv Manual
Author: <insert document author here>
Abstract: This manual describes what pyenv is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pyenv/pyenv.sgml.gz

Format: postscript
Files: /usr/share/doc/pyenv/pyenv.ps.gz

Format: text
Files: /usr/share/doc/pyenv/pyenv.text.gz

Format: HTML
Index: /usr/share/doc/pyenv/html/index.html
Files: /usr/share/doc/pyenv/html/*.html
